### ISSUE TITLE
Vignettes should not show slide content behind them

### ISSUE THREAD

**Issue by bradwiatr** [User10/playable-stories#30]
Currently, it moves to the next slide, then pops up the vignette for the previous slide (which is no longer visible in the background)

**Comment by JoshMountain** [comment]
@bradwiatr This isn't really possible because we don't know what the vignette will say until they pick a choice and we see what happens

**Comment by JoshMountain** [comment]
Lets do this as a design hide/trick

**Comment by bradwiatr** [comment]
Taken care of with commit 5fa705048021650ee2dd378accf729cc7ddcd149
